Repository j23rl07/adri-s-bizarre-adventure, pull requests merged in 2022-04, with the labels that each got.

#66 #58 - feat: Added equipable items
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/ChuletaScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/ChuletaScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/HojaDeEstudioScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/HojaDeEstudioScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/LuckyCoinScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/LuckyCoinScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/MaterialDeEscuelaScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/MaterialDeEscuelaScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/ThermoScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/ThermoScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/TrabajoExtraScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/TrabajoExtraScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/Trinket.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/Trinket.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/TrinketState.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Trinket/TrinketState.cs.meta
  TFG Plataformer/Assets/1. Scripts/Player/Player.cs
  TFG Plataformer/Assets/1. Scripts/Player/ScoreScript.cs
  TFG Plataformer/Assets/4. Resources/TrinketImages.meta
  TFG Plataformer/Assets/4. Resources/TrinketImages/Chuleta.png
  TFG Plataformer/Assets/4. Resources/TrinketImages/Chuleta.png.meta
  TFG Plataformer/Assets/4. Resources/TrinketImages/ExtraWork.png
  TFG Plataformer/Assets/4. Resources/TrinketImages/ExtraWork.png.meta
  TFG Plataformer/Assets/4. Resources/TrinketImages/HojaDeEstudio.png
  TFG Plataformer/Assets/4. Resources/TrinketImages/HojaDeEstudio.png.meta
  TFG Plataformer/Assets/4. Resources/TrinketImages/LuckyCoin.png
  TFG Plataformer/Assets/4. Resources/TrinketImages/LuckyCoin.png.meta
  TFG Plataformer/Assets/4. Resources/TrinketImages/MaterialDeEscuela.png
  TFG Plataformer/Assets/4. Resources/TrinketImages/MaterialDeEscuela.png.meta
  TFG Plataformer/Assets/4. Resources/TrinketImages/Thermo.png
  TFG Plataformer/Assets/4. Resources/TrinketImages/Thermo.png.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets/Chuleta.asset
  TFG Plataformer/Assets/5. Prefabs/Trinkets/Chuleta.asset.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets/HojaDeEstudio.asset
  TFG Plataformer/Assets/5. Prefabs/Trinkets/HojaDeEstudio.asset.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets/MaterialDeEscuela.asset
  TFG Plataformer/Assets/5. Prefabs/Trinkets/MaterialDeEscuela.asset.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets/MonedaDeSuerte.asset
  TFG Plataformer/Assets/5. Prefabs/Trinkets/MonedaDeSuerte.asset.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets/Thermo.asset
  TFG Plataformer/Assets/5. Prefabs/Trinkets/Thermo.asset.meta
  TFG Plataformer/Assets/5. Prefabs/Trinkets/Trabajo extra.asset
  TFG Plataformer/Assets/5. Prefabs/Trinkets/Trabajo extra.asset.meta
  TFG Plataformer/Assets/6. Scenes/References/Interfaz.unity
Labels: enhancement, Sprint 2

#69 #48 boomerang
  TFG Plataformer/Assets/1. Scripts/Player/HealingItemsScript.cs
  TFG Plataformer/Assets/1. Scripts/Player/Player.cs
  TFG Plataformer/Assets/1. Scripts/Player/PlayerMovement.cs
  TFG Plataformer/Assets/1. Scripts/Player/Weapon.cs
  TFG Plataformer/Assets/1. Scripts/Player/Weapon.cs.meta
  TFG Plataformer/Assets/1. Scripts/Skills/BoomerangScript.cs
  TFG Plataformer/Assets/1. Scripts/Skills/BoomerangScript.cs.meta
  TFG Plataformer/Assets/2. Animation/Fireball/impact-1.controller
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/Boomerang.png
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/Boomerang.png.meta
  TFG Plataformer/Assets/5. Prefabs/Player.prefab
  TFG Plataformer/Assets/5. Prefabs/Player.prefab.meta
  TFG Plataformer/Assets/5. Prefabs/Skill/Boomerang.prefab
  TFG Plataformer/Assets/5. Prefabs/Skill/Boomerang.prefab.meta
  TFG Plataformer/Assets/6. Scenes/References/Interfaz.unity
  TFG Plataformer/Assets/Scripts/Player/Weapon.cs
  TFG Plataformer/ProjectSettings/TagManager.asset
Labels: enhancement, Sprint 2

#70 fix - Fixed minor UI, skill and movement issues. UI skill changes.
  TFG Plataformer/Assets/1. Scripts/Player/PlayerMovement.cs
  TFG Plataformer/Assets/1. Scripts/Player/Weapon.cs
  TFG Plataformer/Assets/4. Resources/Skills Images.meta
  TFG Plataformer/Assets/4. Resources/Skills Images/Boomerang.png
  TFG Plataformer/Assets/4. Resources/Skills Images/Boomerang.png.meta
  TFG Plataformer/Assets/4. Resources/Skills Images/cuchillaFolio.png
  TFG Plataformer/Assets/4. Resources/Skills Images/cuchillaFolio.png.meta
  TFG Plataformer/Assets/4. Resources/Skills Images/descarga.png
  TFG Plataformer/Assets/4. Resources/Skills Images/descarga.png.meta
  TFG Plataformer/Assets/4. Resources/Skills Images/fireball.png
  TFG Plataformer/Assets/4. Resources/Skills Images/fireball.png.meta
  TFG Plataformer/Assets/4. Resources/Skills Images/gammaRay.png
  TFG Plataformer/Assets/4. Resources/Skills Images/gammaRay.png.meta
  TFG Plataformer/Assets/4. Resources/Skills Images/horizontalProjectile.png
  TFG Plataformer/Assets/4. Resources/Skills Images/horizontalProjectile.png.meta
  TFG Plataformer/Assets/5. Prefabs/Player FIXED.prefab
  TFG Plataformer/Assets/5. Prefabs/Player FIXED.prefab.meta
  TFG Plataformer/Assets/5. Prefabs/Skill/Cuchilla folio.prefab
  TFG Plataformer/Assets/5. Prefabs/Skill/Descarga.prefab
  TFG Plataformer/Assets/5. Prefabs/Skill/Fireball.prefab
  TFG Plataformer/Assets/5. Prefabs/Skill/GammaRay.prefab
  TFG Plataformer/Assets/5. Prefabs/Skill/HorizontalProjectile.prefab
  TFG Plataformer/Assets/6. Scenes/References/Interfaz.unity
Labels: bug, enhancement, Sprint 2

#104 #94 - feat: Creados prefabs para curar vida y mana
  TFG Plataformer/Assets/1. Scripts/Elements/Zona Descanso.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Zona Descanso/DescansoManaScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Zona Descanso/DescansoManaScript.cs.meta
  TFG Plataformer/Assets/1. Scripts/Elements/Zona Descanso/DescansoVidaScript.cs
  TFG Plataformer/Assets/1. Scripts/Elements/Zona Descanso/DescansoVidaScript.cs.meta
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/bookShelf.png
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/bookShelf.png.meta
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/couch.png
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/couch.png.meta
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/vendignMachine.png
  TFG Plataformer/Assets/4. Resources/ImagenesCustom/vendignMachine.png.meta
  TFG Plataformer/Assets/5. Prefabs/bookShelf.prefab
  TFG Plataformer/Assets/5. Prefabs/bookShelf.prefab.meta
  TFG Plataformer/Assets/5. Prefabs/vendignMachine.prefab
  TFG Plataformer/Assets/5. Prefabs/vendignMachine.prefab.meta
  TFG Plataformer/Assets/6. Scenes/References/Interfaz.unity
Labels: enhancement, Sprint 3
